services:
  - type: web
    name: enviar-correo
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SMTP_USER
        value: contacto@melviolin.com
      - key: SMTP_PASS
        value: ZkND#xgjKLdY
      - key: SMTP_SERVER
        value: melviolin.com
      - key: SMTP_PORT
        value: "465"
